// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SCA.Infrastrucuture.Data;
using System;

namespace SCA.Infrastrucuture.Migrations.Audiencia
{
    [DbContext(typeof(ProcessoContext))]
    [Migration("20180426143335_inicio")]
    partial class inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SCA.ApplicationCore.Entity.Audiencia", b =>
                {
                    b.Property<int>("AudienciaId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<string>("Detalhes");

                    b.HasKey("AudienciaId");

                    b.ToTable("Audiencia");
                });
#pragma warning restore 612, 618
        }
    }
}
